export type Destination = {
  city: string;
  sub: string;
  code: string;
};

export const DESTINATIONS: Destination[] = [
  // USA — Southeast
  { city: "Atlanta", sub: "Georgia, USA", code: "ATL" },
  { city: "Savannah", sub: "Georgia, USA", code: "SAV" },
  { city: "Charleston", sub: "South Carolina, USA", code: "CHS" },
  { city: "Myrtle Beach", sub: "South Carolina, USA", code: "MYR" },
  { city: "Raleigh", sub: "North Carolina, USA", code: "RDU" },
  { city: "Charlotte", sub: "North Carolina, USA", code: "CLT" },
  { city: "Asheville", sub: "North Carolina, USA", code: "AVL" },
  { city: "Outer Banks", sub: "North Carolina, USA", code: "OBX" },
  { city: "Nashville", sub: "Tennessee, USA", code: "BNA" },
  { city: "Memphis", sub: "Tennessee, USA", code: "MEM" },
  { city: "Gatlinburg", sub: "Tennessee, USA", code: "TYS" },
  { city: "New Orleans", sub: "Louisiana, USA", code: "MSY" },
  { city: "Miami", sub: "Florida, USA", code: "MIA" },
  { city: "Orlando", sub: "Florida, USA", code: "MCO" },
  { city: "Tampa", sub: "Florida, USA", code: "TPA" },
  { city: "Key West", sub: "Florida, USA", code: "EYW" },
  { city: "Destin", sub: "Florida, USA", code: "VPS" },
  { city: "Virginia Beach", sub: "Virginia, USA", code: "ORF" },
  { city: "Washington D.C.", sub: "USA", code: "DCA" },
  { city: "Baltimore", sub: "Maryland, USA", code: "BWI" },
  // USA — Northeast
  { city: "New York", sub: "New York, USA", code: "JFK" },
  { city: "Boston", sub: "Massachusetts, USA", code: "BOS" },
  { city: "Philadelphia", sub: "Pennsylvania, USA", code: "PHL" },
  { city: "Providence", sub: "Rhode Island, USA", code: "PVD" },
  { city: "Portland", sub: "Maine, USA", code: "PWM" },
  { city: "Burlington", sub: "Vermont, USA", code: "BTV" },
  // USA — Midwest
  { city: "Chicago", sub: "Illinois, USA", code: "ORD" },
  { city: "Detroit", sub: "Michigan, USA", code: "DTW" },
  { city: "Minneapolis", sub: "Minnesota, USA", code: "MSP" },
  { city: "Columbus", sub: "Ohio, USA", code: "CMH" },
  { city: "Indianapolis", sub: "Indiana, USA", code: "IND" },
  { city: "Kansas City", sub: "Missouri, USA", code: "MCI" },
  { city: "St. Louis", sub: "Missouri, USA", code: "STL" },
  { city: "Milwaukee", sub: "Wisconsin, USA", code: "MKE" },
  // USA — Southwest & Mountain
  { city: "Las Vegas", sub: "Nevada, USA", code: "LAS" },
  { city: "Phoenix", sub: "Arizona, USA", code: "PHX" },
  { city: "Scottsdale", sub: "Arizona, USA", code: "PHX" },
  { city: "Sedona", sub: "Arizona, USA", code: "FLG" },
  { city: "Grand Canyon", sub: "Arizona, USA", code: "GCN" },
  { city: "Denver", sub: "Colorado, USA", code: "DEN" },
  { city: "Aspen", sub: "Colorado, USA", code: "ASE" },
  { city: "Telluride", sub: "Colorado, USA", code: "TEX" },
  { city: "Breckenridge", sub: "Colorado, USA", code: "DEN" },
  { city: "Austin", sub: "Texas, USA", code: "AUS" },
  { city: "Dallas", sub: "Texas, USA", code: "DFW" },
  { city: "Houston", sub: "Texas, USA", code: "IAH" },
  { city: "San Antonio", sub: "Texas, USA", code: "SAT" },
  { city: "Albuquerque", sub: "New Mexico, USA", code: "ABQ" },
  { city: "Santa Fe", sub: "New Mexico, USA", code: "SAF" },
  { city: "Salt Lake City", sub: "Utah, USA", code: "SLC" },
  { city: "Moab", sub: "Utah, USA", code: "CNY" },
  { city: "Park City", sub: "Utah, USA", code: "SLC" },
  // USA — West Coast
  { city: "Los Angeles", sub: "California, USA", code: "LAX" },
  { city: "San Francisco", sub: "California, USA", code: "SFO" },
  { city: "San Diego", sub: "California, USA", code: "SAN" },
  { city: "Napa", sub: "California, USA", code: "SFO" },
  { city: "Lake Tahoe", sub: "California, USA", code: "RNO" },
  { city: "Palm Springs", sub: "California, USA", code: "PSP" },
  { city: "Seattle", sub: "Washington, USA", code: "SEA" },
  { city: "Portland", sub: "Oregon, USA", code: "PDX" },
  // USA — Hawaii & Alaska
  { city: "Honolulu", sub: "Hawaii, USA", code: "HNL" },
  { city: "Maui", sub: "Hawaii, USA", code: "OGG" },
  { city: "Kauai", sub: "Hawaii, USA", code: "LIH" },
  { city: "Anchorage", sub: "Alaska, USA", code: "ANC" },
  // Caribbean
  { city: "Cancún", sub: "Mexico", code: "CUN" },
  { city: "Cabo San Lucas", sub: "Mexico", code: "SJD" },
  { city: "Mexico City", sub: "Mexico", code: "MEX" },
  { city: "Tulum", sub: "Mexico", code: "CUN" },
  { city: "Puerto Vallarta", sub: "Mexico", code: "PVR" },
  { city: "Punta Cana", sub: "Dominican Republic", code: "PUJ" },
  { city: "Santo Domingo", sub: "Dominican Republic", code: "SDQ" },
  { city: "San Juan", sub: "Puerto Rico", code: "SJU" },
  { city: "Nassau", sub: "Bahamas", code: "NAS" },
  { city: "Montego Bay", sub: "Jamaica", code: "MBJ" },
  { city: "Kingston", sub: "Jamaica", code: "KIN" },
  { city: "Bridgetown", sub: "Barbados", code: "BGI" },
  { city: "Providenciales", sub: "Turks & Caicos", code: "PLS" },
  { city: "Road Town", sub: "British Virgin Islands", code: "EIS" },
  { city: "St. George's", sub: "Grenada", code: "GND" },
  { city: "Castries", sub: "St. Lucia", code: "SLU" },
  { city: "Basseterre", sub: "St. Kitts", code: "SKB" },
  { city: "Willemstad", sub: "Curaçao", code: "CUR" },
  { city: "Oranjestad", sub: "Aruba", code: "AUA" },
  { city: "Havana", sub: "Cuba", code: "HAV" },
  // Europe — Western
  { city: "London", sub: "United Kingdom", code: "LHR" },
  { city: "Edinburgh", sub: "Scotland, UK", code: "EDI" },
  { city: "Dublin", sub: "Ireland", code: "DUB" },
  { city: "Paris", sub: "France", code: "CDG" },
  { city: "Nice", sub: "France", code: "NCE" },
  { city: "Lyon", sub: "France", code: "LYS" },
  { city: "Amsterdam", sub: "Netherlands", code: "AMS" },
  { city: "Brussels", sub: "Belgium", code: "BRU" },
  { city: "Bruges", sub: "Belgium", code: "BRU" },
  { city: "Zurich", sub: "Switzerland", code: "ZRH" },
  { city: "Geneva", sub: "Switzerland", code: "GVA" },
  { city: "Interlaken", sub: "Switzerland", code: "ZRH" },
  { city: "Vienna", sub: "Austria", code: "VIE" },
  { city: "Salzburg", sub: "Austria", code: "SZG" },
  { city: "Barcelona", sub: "Spain", code: "BCN" },
  { city: "Madrid", sub: "Spain", code: "MAD" },
  { city: "Seville", sub: "Spain", code: "SVQ" },
  { city: "Ibiza", sub: "Spain", code: "IBZ" },
  { city: "Mallorca", sub: "Spain", code: "PMI" },
  { city: "Lisbon", sub: "Portugal", code: "LIS" },
  { city: "Porto", sub: "Portugal", code: "OPO" },
  { city: "Algarve", sub: "Portugal", code: "FAO" },
  { city: "Rome", sub: "Italy", code: "FCO" },
  { city: "Milan", sub: "Italy", code: "MXP" },
  { city: "Florence", sub: "Italy", code: "FLR" },
  { city: "Venice", sub: "Italy", code: "VCE" },
  { city: "Naples", sub: "Italy", code: "NAP" },
  { city: "Amalfi Coast", sub: "Italy", code: "NAP" },
  { city: "Cinque Terre", sub: "Italy", code: "GNO" },
  { city: "Sicily", sub: "Italy", code: "CTA" },
  { city: "Sardinia", sub: "Italy", code: "CAG" },
  // Europe — Northern
  { city: "Reykjavík", sub: "Iceland", code: "KEF" },
  { city: "Copenhagen", sub: "Denmark", code: "CPH" },
  { city: "Stockholm", sub: "Sweden", code: "ARN" },
  { city: "Oslo", sub: "Norway", code: "OSL" },
  { city: "Bergen", sub: "Norway", code: "BGO" },
  { city: "Helsinki", sub: "Finland", code: "HEL" },
  { city: "Tallinn", sub: "Estonia", code: "TLL" },
  { city: "Riga", sub: "Latvia", code: "RIX" },
  { city: "Vilnius", sub: "Lithuania", code: "VNO" },
  // Europe — Eastern & Central
  { city: "Prague", sub: "Czech Republic", code: "PRG" },
  { city: "Budapest", sub: "Hungary", code: "BUD" },
  { city: "Krakow", sub: "Poland", code: "KRK" },
  { city: "Warsaw", sub: "Poland", code: "WAW" },
  { city: "Bucharest", sub: "Romania", code: "OTP" },
  { city: "Sofia", sub: "Bulgaria", code: "SOF" },
  { city: "Athens", sub: "Greece", code: "ATH" },
  { city: "Santorini", sub: "Greece", code: "JTR" },
  { city: "Mykonos", sub: "Greece", code: "JMK" },
  { city: "Crete", sub: "Greece", code: "HER" },
  { city: "Rhodes", sub: "Greece", code: "RHO" },
  { city: "Dubrovnik", sub: "Croatia", code: "DBV" },
  { city: "Split", sub: "Croatia", code: "SPU" },
  { city: "Hvar", sub: "Croatia", code: "SPU" },
  { city: "Ljubljana", sub: "Slovenia", code: "LJU" },
  { city: "Sarajevo", sub: "Bosnia", code: "SJJ" },
  { city: "Belgrade", sub: "Serbia", code: "BEG" },
  { city: "Istanbul", sub: "Turkey", code: "IST" },
  { city: "Cappadocia", sub: "Turkey", code: "ASR" },
  { city: "Antalya", sub: "Turkey", code: "AYT" },
  // Middle East & Africa
  { city: "Dubai", sub: "UAE", code: "DXB" },
  { city: "Abu Dhabi", sub: "UAE", code: "AUH" },
  { city: "Doha", sub: "Qatar", code: "DOH" },
  { city: "Marrakech", sub: "Morocco", code: "RAK" },
  { city: "Casablanca", sub: "Morocco", code: "CMN" },
  { city: "Cairo", sub: "Egypt", code: "CAI" },
  { city: "Cape Town", sub: "South Africa", code: "CPT" },
  { city: "Johannesburg", sub: "South Africa", code: "JNB" },
  { city: "Nairobi", sub: "Kenya", code: "NBO" },
  { city: "Zanzibar", sub: "Tanzania", code: "ZNZ" },
  { city: "Serengeti", sub: "Tanzania", code: "JRO" },
  { city: "Tel Aviv", sub: "Israel", code: "TLV" },
  // Asia
  { city: "Tokyo", sub: "Japan", code: "NRT" },
  { city: "Kyoto", sub: "Japan", code: "ITM" },
  { city: "Osaka", sub: "Japan", code: "KIX" },
  { city: "Seoul", sub: "South Korea", code: "ICN" },
  { city: "Beijing", sub: "China", code: "PEK" },
  { city: "Shanghai", sub: "China", code: "PVG" },
  { city: "Hong Kong", sub: "China", code: "HKG" },
  { city: "Bangkok", sub: "Thailand", code: "BKK" },
  { city: "Phuket", sub: "Thailand", code: "HKT" },
  { city: "Chiang Mai", sub: "Thailand", code: "CNX" },
  { city: "Bali", sub: "Indonesia", code: "DPS" },
  { city: "Singapore", sub: "Singapore", code: "SIN" },
  { city: "Kuala Lumpur", sub: "Malaysia", code: "KUL" },
  { city: "Hanoi", sub: "Vietnam", code: "HAN" },
  { city: "Ho Chi Minh City", sub: "Vietnam", code: "SGN" },
  { city: "Hoi An", sub: "Vietnam", code: "DAD" },
  { city: "Colombo", sub: "Sri Lanka", code: "CMB" },
  { city: "Mumbai", sub: "India", code: "BOM" },
  { city: "Delhi", sub: "India", code: "DEL" },
  { city: "Goa", sub: "India", code: "GOI" },
  { city: "Maldives", sub: "Maldives", code: "MLE" },
  // Oceania
  { city: "Sydney", sub: "Australia", code: "SYD" },
  { city: "Melbourne", sub: "Australia", code: "MEL" },
  { city: "Brisbane", sub: "Australia", code: "BNE" },
  { city: "Gold Coast", sub: "Australia", code: "OOL" },
  { city: "Cairns", sub: "Australia", code: "CNS" },
  { city: "Auckland", sub: "New Zealand", code: "AKL" },
  { city: "Queenstown", sub: "New Zealand", code: "ZQN" },
  // Canada
  { city: "Toronto", sub: "Ontario, Canada", code: "YYZ" },
  { city: "Vancouver", sub: "British Columbia, Canada", code: "YVR" },
  { city: "Montreal", sub: "Quebec, Canada", code: "YUL" },
  { city: "Calgary", sub: "Alberta, Canada", code: "YYC" },
  { city: "Banff", sub: "Alberta, Canada", code: "YYC" },
  { city: "Quebec City", sub: "Quebec, Canada", code: "YQB" },
  // South America
  { city: "Rio de Janeiro", sub: "Brazil", code: "GIG" },
  { city: "São Paulo", sub: "Brazil", code: "GRU" },
  { city: "Buenos Aires", sub: "Argentina", code: "EZE" },
  { city: "Patagonia", sub: "Argentina/Chile", code: "USH" },
  { city: "Lima", sub: "Peru", code: "LIM" },
  { city: "Cusco", sub: "Peru", code: "CUZ" },
  { city: "Machu Picchu", sub: "Peru", code: "CUZ" },
  { city: "Bogotá", sub: "Colombia", code: "BOG" },
  { city: "Cartagena", sub: "Colombia", code: "CTG" },
  { city: "Medellín", sub: "Colombia", code: "MDE" },
  { city: "Santiago", sub: "Chile", code: "SCL" },
  { city: "Quito", sub: "Ecuador", code: "UIO" },
  { city: "Galápagos Islands", sub: "Ecuador", code: "GPS" },
];

export function searchDestinations(query: string): Destination[] {
  const q = query.trim().toLowerCase();
  if (!q) return DESTINATIONS.slice(0, 6);
  return DESTINATIONS.filter(d =>
    (d.city + " " + d.sub + " " + d.code).toLowerCase().includes(q)
  ).slice(0, 6);
}
